- hosts: all
  become: true
  tasks:
    - name: Install apache2 software Debian/Ubuntu
      apt:
        name: apache2
        state: present
    - name : Restart apache 
      service: 
        name : apache2
        state: started
